import type { GenerateOptions } from "../PdfGenerator";
import type { SeasonWrapped } from "../../domain/SeasonWrapped";
import { readFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Helper function to load optimized images as base64
function getImageAsBase64(filename: string): string {
    try {
        const imagePath = join(__dirname, 'optimized', filename);
        if (!existsSync(imagePath)) return '';
        const imageBuffer = readFileSync(imagePath);
        const base64 = imageBuffer.toString('base64');
        return `data:image/png;base64,${base64}`;
    } catch (error) {
        console.error(`Failed to load image ${filename}:`, error);
        return '';
    }
}

// Pre-load optimized Yu-Gi-Oh! themed images
const images = {
    decorative1: getImageAsBase64('yugioh_dragon_background.png'),      // Dragon artwork
    decorative2: getImageAsBase64('yugioh_monster_background.png'),     // Monster artwork
    decorative3: getImageAsBase64('yugioh_battlefield_background.png'), // Battlefield scene
    decorative4: getImageAsBase64('yugioh_cards_background.png'),       // Cards artwork
    icon: getImageAsBase64('yugioh_chapter_icon.png'),                  // Small chapter icon
};

export function renderTemplate(data: SeasonWrapped, options: GenerateOptions): string {
    const styles = readFileSync(join(__dirname, "styles.css"), "utf-8");

    return `
<!DOCTYPE html>
<html lang="${options.locale}">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Season ${data.seasonId} Wrapped - ${data.playerName}</title>
	<style>${styles}</style>
</head>
<body>
	${renderCoverPage(data, options)}
	${renderGlobalStatsPage(data, options)}
	${renderBanListPages(data, options)}
	${renderChartsPage(data, options)}
    ${(data.nemesis || data.victim) ? renderRivalsPage(data, options) : ""}
    ${data.achievements.length > 0 ? renderAchievementsPage(data, options) : ""}
	${renderRankingPage(data, options)}
	${renderSummaryPage(data, options)}
</body>
</html>
	`.trim();
}

// Single-page compact version for evaluation
export function renderSinglePageTemplate(data: SeasonWrapped, options: GenerateOptions): string {
    const styles = readFileSync(join(__dirname, "styles.css"), "utf-8");
    const singlePageStyles = readFileSync(join(__dirname, "styles_single_page.css"), "utf-8");

    return `
<!DOCTYPE html>
<html lang="${options.locale}">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Season ${data.seasonId} Wrapped - ${data.playerName} (Single Page)</title>
	<style>${styles}</style>
	<style>${singlePageStyles}</style>
</head>
<body>
	${renderCoverPage(data, options)}
	${renderGlobalStatsPage(data, options)}
	${renderBanListPages(data, options)}
	${renderChartsPage(data, options)}
    ${(data.nemesis || data.victim) ? renderRivalsPage(data, options) : ""}
    ${data.achievements.length > 0 ? renderAchievementsPage(data, options) : ""}
    ${renderRankingPage(data, options)}
</body>
</html>
	`.trim();
}

function renderHeader(title: string, seasonName: string, _options: GenerateOptions): string {
    return `
    <div class="header-bar">
        <div class="brand">
            <span class="brand-icon">◆</span>
            DUELIST WRAPPED
        </div>
        <div class="season-tag">${seasonName}</div>
    </div>
    `;
}

function renderCoverPage(data: SeasonWrapped, options: GenerateOptions): string {
    const avatarSrc = data.playerAvatar || getInitialsAvatar(data.playerName);

    return `
<div class="page cover-page">
	${images.decorative1 ? `<div class="page-bg-decoration"><img src="${images.decorative1}" alt="" /></div>` : ''}

	<img src="${avatarSrc}" alt="${data.playerName}" class="cover-avatar" />
	
	<h1 class="cover-title">${options.locale === "es" ? "TU AÑO EN DUELOS" : "YOUR DUELING YEAR"}</h1>
	
	<p class="subtitle" style="font-size: 24px; color: var(--text-secondary);">
		${data.playerName} · ${data.seasonName}
	</p>
    
    <div class="footer">
        Generated by Evolution API
    </div>
</div>
	`;
}

function renderGlobalStatsPage(data: SeasonWrapped, options: GenerateOptions): string {
    const stats = data.globalStats;

    return `
<div class="page">
    ${images.decorative2 ? `<div class="page-bg-decoration"><img src="${images.decorative2}" alt="" /></div>` : ''}
    ${renderHeader("Season Overview", data.seasonName, options)}

	<div class="chapter-super">
		${images.icon ? `<img src="${images.icon}" class="chapter-icon" alt="" />` : ''}
		${options.locale === "es" ? "CAPÍTULO 1" : "CHAPTER 1"}
	</div>
	<h2 class="page-title">${options.locale === "es" ? "Resumen de Temporada" : "Season Overview"}</h2>
	
    <div class="main-stats-card">
        <div class="tag-badge">
            ${stats.totalMatches} ${options.locale === "es" ? "PARTIDAS TOTALES" : "TOTAL MATCHES"}
        </div>
        
        <div class="big-stats-row">
            <div class="stat-group">
                <span class="stat-group-label">${options.locale === "es" ? "VICTORIAS" : "WINS"}</span>
                <span class="stat-group-value wins">${stats.wins}</span>
            </div>
            <div class="stat-group">
                <span class="stat-group-label">${options.locale === "es" ? "DERROTAS" : "LOSSES"}</span>
                <span class="stat-group-value losses">${stats.losses}</span>
            </div>
        </div>

        <div class="winrate-section">
            <div class="winrate-header">
                <span>WINRATE</span>
                <span>${stats.winrate}%</span>
            </div>
            <div class="progress-track">
                <div class="progress-fill" style="width: ${stats.winrate}%"></div>
            </div>
        </div>
    </div>

    <div class="grid-2">
        <div class="stat-box">
            <div class="stat-box-icon">🔥</div>
            <div class="stat-box-label">${options.locale === "es" ? "Mejor Racha" : "Best Streak"}</div>
            <div class="stat-box-value">${stats.bestWinStreak}</div>
            <div class="stat-box-sub">${options.locale === "es" ? "Victorias seguidas" : "Wins in a row"}</div>
        </div>
        <div class="stat-box">
             <div class="stat-box-icon">📅</div>
            <div class="stat-box-label">${options.locale === "es" ? "Días Activos" : "Active Days"}</div>
            <div class="stat-box-value">${stats.activeDays}</div>
            <div class="stat-box-sub">${options.locale === "es" ? "Días jugados" : "Days played"}</div>
        </div>
    </div>
</div>
	`;
}

function renderBanListPages(data: SeasonWrapped, options: GenerateOptions): string {
    if (data.banListStats.length === 0) return "";

    // Take top 3 banlists to fit on one page if possible, or paginate
    const topBanlist = data.banListStats[0];

    return `
<div class="page">
    ${images.decorative3 ? `<div class="page-bg-decoration"><img src="${images.decorative3}" alt="" /></div>` : ''}
    ${renderHeader("Formats", data.seasonName, options)}
    
	<div class="chapter-super">
		${images.icon ? `<img src="${images.icon}" class="chapter-icon" alt="" />` : ''}
		${options.locale === "es" ? "CAPÍTULO 2" : "CHAPTER 2"}
	</div>
	<h2 class="page-title">${options.locale === "es" ? "Formatos Dominados" : "Mastered Formats"}</h2>
	
	<div class="card-container">
        <div class="tag-badge">MAIN FORMAT</div>
        
        <h3 style="font-size: 32px; font-weight: 800; margin-bottom: 8px;">${escapeHtml(topBanlist.banListName)}</h3>
        <p style="color: var(--text-secondary); margin-bottom: 24px;">${topBanlist.getFlavor()}</p>
        
        <div class="winrate-section" style="margin: 0; max-width: 100%;">
            <div class="winrate-header">
                <span>WINRATE (${topBanlist.matches} matches)</span>
                <span>${topBanlist.winrate}%</span>
            </div>
            <div class="progress-track" style="background: rgba(255,255,255,0.1)">
                <div class="progress-fill" style="width: ${topBanlist.winrate}%"></div>
            </div>
        </div>
	</div>

    <div class="grid-2" style="margin-top: 24px;">
        ${data.banListStats.slice(1, 3).map(bl => `
        <div class="stat-box">
            <div class="stat-box-label">${escapeHtml(bl.banListName)}</div>
            <div class="stat-box-value" style="font-size: 32px;">${bl.winrate}%</div>
            <div class="stat-box-sub">${bl.matches} matches</div>
        </div>
        `).join('')}
    </div>
</div>
	`;
}

function renderRivalsPage(data: SeasonWrapped, options: GenerateOptions): string {
    return `
<div class="page">
    ${images.decorative4 ? `<div class="page-bg-decoration"><img src="${images.decorative4}" alt="" /></div>` : ''}
    ${renderHeader("Rivals", data.seasonName, options)}

    <div class="chapter-super">
		${images.icon ? `<img src="${images.icon}" class="chapter-icon" alt="" />` : ''}
		${options.locale === "es" ? "CAPÍTULO 3" : "CHAPTER 3"}
	</div>
    <h2 class="page-title">${options.locale === "es" ? "Tus Rivales" : "Your Rivals"}</h2>

    ${data.nemesis ? `
    <div class="card-container" style="margin-bottom: 24px;">
        <div class="tag-badge" style="color: #ef4444; background: rgba(239, 68, 68, 0.1); border-color: rgba(239, 68, 68, 0.2);">
            👻 SEASON NEMESIS
        </div>
        
        <div class="profile-card" style="border: none; background: transparent; padding: 0;">
            <img src="${data.nemesis.playerAvatar || getInitialsAvatar(data.nemesis.playerName)}" class="profile-avatar" style="border-color: #ef4444;" />
            
            <div class="profile-info">
                <h3 style="color: #ef4444;">${escapeHtml(data.nemesis.playerName)}</h3>
                <div class="profile-stats-row">
                    <span class="pill">${data.nemesis.totalMatches} matches</span>
                    <span class="pill" style="background: rgba(239, 68, 68, 0.2); color: #ef4444;">${data.nemesis.losses} losses</span>
                </div>
            </div>
        </div>
    </div>
    ` : ""}

    ${data.victim ? `
    <div class="card-container">
        <div class="tag-badge" style="color: #10b981; background: rgba(16, 185, 129, 0.1); border-color: rgba(16, 185, 129, 0.2);">
            🎯 SEASON VICTIM
        </div>
         <div class="profile-card" style="border: none; background: transparent; padding: 0;">
            <img src="${data.victim.playerAvatar || getInitialsAvatar(data.victim.playerName)}" class="profile-avatar" style="border-color: #10b981;" />
            
            <div class="profile-info">
                <h3 style="color: #10b981;">${escapeHtml(data.victim.playerName)}</h3>
                <div class="profile-stats-row">
                    <span class="pill">${data.victim.totalMatches} matches</span>
                    <span class="pill" style="background: rgba(16, 185, 129, 0.2); color: #10b981;">${data.victim.wins} wins</span>
                </div>
            </div>
        </div>
    </div>
    ` : ""}
</div>
    `;
}

function renderChartsPage(data: SeasonWrapped, options: GenerateOptions): string {
    if (data.banListStats.length === 0) return "";

    // Calculate max matches for scaling
    const maxMatches = Math.max(...data.banListStats.map(bl => bl.matches));

    return `
<div class="page">
    ${renderHeader("Evolution", data.seasonName, options)}
    
    <div class="chapter-super">${options.locale === "es" ? "CAPÍTULO 4" : "CHAPTER 4"}</div>
    <h2 class="page-title">${options.locale === "es" ? "Evolución" : "Evolution"}</h2>
    
    <div class="card-container">
        <h3 style="margin-bottom: 24px;">Matches Distribution</h3>
        
        ${data.banListStats.map(bl => `
        <div class="chart-bar-item">
            <div class="chart-bar-header">
                <span>${escapeHtml(bl.banListName)}</span>
                <span style="color: var(--text-muted);">${bl.matches}</span>
            </div>
            <div class="chart-track">
                <div class="chart-fill active" style="width: ${(bl.matches / maxMatches) * 100}%"></div>
            </div>
        </div>
        `).join('')}
    </div>
</div>
    `;
}

function renderAchievementsPage(data: SeasonWrapped, options: GenerateOptions): string {
    if (data.achievements.length === 0) return "";

    return `
<div class="page">
    ${renderHeader("Logros", data.seasonName, options)}
    
    <div class="chapter-super">${options.locale === "es" ? "CAPÍTULO 5" : "CHAPTER 5"}</div>
    <h2 class="page-title">${options.locale === "es" ? "Logros" : "Achievements"}</h2>
    
    <div class="achievements-grid">
        ${data.achievements.map(ach => `
        <div class="stat-box" style="display: flex; gap: 16px; align-items: start;">
            <div style="font-size: 32px;">${ach.icon}</div>
            <div>
                <div style="font-weight: 700; margin-bottom: 4px;">${escapeHtml(ach.name)}</div>
                <div style="font-size: 12px; color: var(--text-secondary); line-height: 1.4;">${escapeHtml(ach.description)}</div>
                <div style="font-size: 10px; color: var(--text-muted); margin-top: 8px;">${formatDate(ach.unlockedAt)}</div>
            </div>
        </div>
        `).join('')}
    </div>
</div>
    `;
}

function renderRankingPage(data: SeasonWrapped, options: GenerateOptions): string {
    return `
<div class="page">
    ${renderHeader("Ranking", data.seasonName, options)}
    
    <div class="chapter-super">${options.locale === "es" ? "FINAL" : "FINALE"}</div>
    <h2 class="page-title">${options.locale === "es" ? "Posición" : "Ranking"}</h2>
    
    <div class="card-container" style="text-align: center; padding: 48px;">
        <div class="tag-badge" style="background: var(--color-accent); color: white; padding: 8px 16px;">
            ${data.ranking.rankBadge} TIER
        </div>
        
        <div style="font-size: 120px; font-weight: 900; line-height: 1; letter-spacing: -4px; margin: 24px 0;">
            #${data.ranking.position}
        </div>
        
        <p style="color: var(--text-secondary); font-size: 20px;">
            Top ${(data.ranking.position / data.ranking.totalPlayers * 100).toFixed(0)}% of ${data.ranking.totalPlayers} players
        </p>
        
        <div style="margin-top: 32px; padding-top: 32px; border-top: 1px solid var(--border-subtle);">
            <div class="stat-group-value" style="font-size: 48px;">${data.ranking.points}</div>
            <div class="stat-group-label" style="margin-top: 8px;">TOTAL POINTS</div>
        </div>
    </div>
    
    ${data.extraStats.uniqueOpponents > 0 ? `
    <div class="grid-2" style="margin-top: 24px;">
        <div class="stat-box">
             <div class="stat-box-label">Unique Opponents</div>
             <div class="stat-box-value">${data.extraStats.uniqueOpponents}</div>
        </div>
        ${data.extraStats.bestDay ? `
        <div class="stat-box">
             <div class="stat-box-label">Lucky Day</div>
             <div class="stat-box-value" style="font-size: 24px;">${escapeHtml(data.extraStats.bestDay)}</div>
        </div>
        ` : ""}
    </div>
    ` : ""}
</div>
    `;
}

function renderSummaryPage(data: SeasonWrapped, options: GenerateOptions): string {
    return `
<div class="page summary-page">
    ${images.decorative1 ? `<div class="page-bg-decoration"><img src="${images.decorative1}" alt="" /></div>` : ''}
    
    <div class="cover-container">
        <img src="${data.playerAvatar || getInitialsAvatar(data.playerName)}" alt="${data.playerName}" class="cover-avatar" />
        
        <div class="subtitle" style="margin-top: 0;">${data.playerName} · ${data.seasonName}</div>
    </div>
        
        <div class="summary-stats-grid">
            <div class="summary-stat-box primary">
                <div class="summary-stat-value">${data.globalStats.totalMatches}</div>
                <div class="summary-stat-label">${options.locale === "es" ? "Duelos" : "Duels"}</div>
            </div>
            
            <div class="summary-stat-box success">
                <div class="summary-stat-value">${data.globalStats.wins}</div>
                <div class="summary-stat-label">${options.locale === "es" ? "Victorias" : "Wins"}</div>
            </div>
            
            <div class="summary-stat-box">
                <div class="summary-stat-value">${data.globalStats.winrate}%</div>
                <div class="summary-stat-label">Win Rate</div>
            </div>
        </div>
        
        <div class="summary-highlights">
            ${data.globalStats.bestWinStreak > 0 ? `
            <div class="summary-highlight">
                🔥 <strong>${data.globalStats.bestWinStreak}</strong> ${options.locale === "es" ? "racha de victorias" : "win streak"}
            </div>
            ` : ''}
            
            ${data.ranking ? `
            <div class="summary-highlight">
                🏆 <strong>#${data.ranking.position}</strong> ${options.locale === "es" ? "en el ranking" : "in rankings"} · ${data.ranking.rankBadge}
            </div>
            ` : ''}
            
            ${data.extraStats?.mostPlayedBanList ? `
            <div class="summary-highlight">
                🎮 ${options.locale === "es" ? "Formato favorito:" : "Favorite format:"} <strong>${data.extraStats.mostPlayedBanList}</strong>
            </div>
            ` : ''}
        </div>
        
        ${(data.nemesis || data.victim) ? `
        <div class="summary-rivals">
            ${data.nemesis ? `
            <div class="summary-rival nemesis">
                <div class="summary-rival-badge">👻</div>
                <div class="summary-rival-info">
                    <div class="summary-rival-label">${options.locale === "es" ? "Némesis" : "Nemesis"}</div>
                    <div class="summary-rival-name">${escapeHtml(data.nemesis.playerName)}</div>
                    <div class="summary-rival-stat">${data.nemesis.wins}W / ${data.nemesis.losses}L</div>
                </div>
            </div>
            ` : ''}
            
            ${data.victim ? `
            <div class="summary-rival victim">
                <div class="summary-rival-badge">🎯</div>
                <div class="summary-rival-info">
                    <div class="summary-rival-label">${options.locale === "es" ? "Víctima" : "Victim"}</div>
                    <div class="summary-rival-name">${escapeHtml(data.victim.playerName)}</div>
                    <div class="summary-rival-stat">${data.victim.wins}W / ${data.victim.losses}L</div>
                </div>
            </div>
            ` : ''}
        </div>
        ` : ''}
        
        <div class="summary-footer">
            <div class="summary-branding">Evolution API</div>
            <div class="summary-season-dates">
                ${new Date(data.seasonDates.start).toLocaleDateString(options.locale === "es" ? "es-ES" : "en-US", { month: 'short', day: 'numeric' })} - 
                ${new Date(data.seasonDates.end).toLocaleDateString(options.locale === "es" ? "es-ES" : "en-US", { month: 'short', day: 'numeric', year: 'numeric' })}
            </div>
        </div>
    </div>
</div>
    `;
}

function getInitialsAvatar(name: string): string {
    return `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' fill='%231e293b'/%3E%3Ctext x='50' y='55' text-anchor='middle' fill='white' font-size='40' font-family='sans-serif' font-weight='bold'%3E${name.charAt(0).toUpperCase()}%3C/text%3E%3C/svg%3E`;
}

function escapeHtml(text: string): string {
    const map: Record<string, string> = {
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#039;",
    };
    return text.replace(/[&<>"']/g, (char) => map[char] || char);
}

function formatDate(date: Date): string {
    return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(date));
}
