name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Copy .env.test
        run: cp .env.test .env

      - name: Run tests
        run: bun test --setup=test/setup.ts

      # Optional: Build step
      - name: Build
        run: bun run build
